/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yeni;

/**
 *
 * @author Furkan Turkmen
 */
public class GrisEkrani extends javax.swing.JFrame {
    Islemler islemler = new Islemler();
    /**
     * Creates new form GrisEkrani
     */
    public GrisEkrani() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        email_label = new javax.swing.JTextField();
        email_alani = new javax.swing.JTextField();
        sifre_label = new javax.swing.JTextField();
        sifre_alani = new javax.swing.JPasswordField();
        giris_buttonu = new javax.swing.JButton();
        uyari_mesaji = new javax.swing.JLabel();
        kayitOl_buttonu = new javax.swing.JButton();
        ana_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 200, 0, 0));
        setMinimumSize(new java.awt.Dimension(616, 425));
        setPreferredSize(new java.awt.Dimension(617, 411));

        jPanel1.setMinimumSize(new java.awt.Dimension(617, 411));
        jPanel1.setLayout(null);

        email_label.setEditable(false);
        email_label.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        email_label.setText("Email :");
        email_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_labelActionPerformed(evt);
            }
        });
        jPanel1.add(email_label);
        email_label.setBounds(160, 30, 80, 30);

        email_alani.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(email_alani);
        email_alani.setBounds(250, 30, 200, 30);

        sifre_label.setEditable(false);
        sifre_label.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sifre_label.setText("Sifre :");
        jPanel1.add(sifre_label);
        sifre_label.setBounds(160, 70, 80, 30);

        sifre_alani.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(sifre_alani);
        sifre_alani.setBounds(250, 70, 200, 30);

        giris_buttonu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        giris_buttonu.setText("Giris");
        giris_buttonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_buttonuActionPerformed(evt);
            }
        });
        jPanel1.add(giris_buttonu);
        giris_buttonu.setBounds(160, 120, 140, 30);

        uyari_mesaji.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        uyari_mesaji.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(uyari_mesaji);
        uyari_mesaji.setBounds(150, 260, 310, 20);

        kayitOl_buttonu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kayitOl_buttonu.setText("Kayit Ol");
        kayitOl_buttonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitOl_buttonuActionPerformed(evt);
            }
        });
        jPanel1.add(kayitOl_buttonu);
        kayitOl_buttonu.setBounds(310, 120, 140, 30);

        ana_label.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ana_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/netflixgiris.png"))); // NOI18N
        jPanel1.add(ana_label);
        ana_label.setBounds(0, 0, 620, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giris_buttonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_buttonuActionPerformed
         if(email_alani.getText().equals("")) {
              uyari_mesaji.setText("Lutfen email alanini doldurunuz.");
              return;
         }
         else if (new String(sifre_alani.getPassword()).equals("")){
             uyari_mesaji.setText("Lutfen sifre alanini doldurunuz.");
              return;
         }
         uyari_mesaji.setText("");
         String email = email_alani.getText();
         String sifre = new String(sifre_alani.getPassword());
         int girisbasarliMi = islemler.girisyap(email, sifre);
         if(girisbasarliMi == 0) {
             uyari_mesaji.setText("Email bulunamadi, Lutfen kayit olunuz!");
         }
         else if(girisbasarliMi == 1){
             uyari_mesaji.setText("Sifre hatali...Lutfen tekrar deneyiniz...");
         } 
         else {
             
             setVisible(false);
             NetflixEkrani netflixEkrani = new NetflixEkrani();
             netflixEkrani.setVisible(true);
         }
          email_alani.setText("");
          sifre_alani.setText("");
    }//GEN-LAST:event_giris_buttonuActionPerformed

    private void email_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_labelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_labelActionPerformed

    private void kayitOl_buttonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitOl_buttonuActionPerformed
         setVisible(false);
         KayitEkrani kayit = new KayitEkrani();
         kayit.setVisible(true);
         
    }//GEN-LAST:event_kayitOl_buttonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ana_label;
    private javax.swing.JTextField email_alani;
    private javax.swing.JTextField email_label;
    private javax.swing.JButton giris_buttonu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kayitOl_buttonu;
    private javax.swing.JPasswordField sifre_alani;
    private javax.swing.JTextField sifre_label;
    private javax.swing.JLabel uyari_mesaji;
    // End of variables declaration//GEN-END:variables
}
