package yeni;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Furkan Turkmen
 */
public class KayitEkrani extends javax.swing.JFrame {

    String dogumtarihi = "YYYY-AA-GG";
    Islemler islemler = new Islemler();
    Set<String> turler = new TreeSet<String>();
    boolean bastiMi = false;

    /**
     * Creates new form KayitEkrani
     */
    public KayitEkrani() {
        initComponents();
        turler = islemler.turAl();
        for (String s : turler) {
            tur1_alani.addItem(s);
            Object cmboitem = tur1_alani.getSelectedItem();
        }
        for (String s : turler) {
            tur2_alani.addItem(s);
            Object cmboitem = tur1_alani.getSelectedItem();
        }
        for (String s : turler) {
            tur3_alani.addItem(s);
            Object cmboitem = tur1_alani.getSelectedItem();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        ad_alani = new javax.swing.JTextField();
        email_alani = new javax.swing.JTextField();
        dogumTarihi_alani = new javax.swing.JTextField();
        sifre_alani = new javax.swing.JPasswordField();
        tur1_alani = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        tur2_alani = new javax.swing.JComboBox<>();
        tur3_alani = new javax.swing.JComboBox<>();
        kayitOl_alani = new javax.swing.JButton();
        girisyap_alani = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        eniyiler = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 700));

        jPanel1.setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField1.setText("Ad :");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(320, 90, 130, 30);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField2.setText("Email :");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(320, 130, 130, 30);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField3.setText("Sifre :");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(320, 170, 130, 30);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField4.setText("Dogum Tarihi :");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(320, 210, 130, 30);

        ad_alani.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(ad_alani);
        ad_alani.setBounds(460, 90, 170, 30);

        email_alani.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(email_alani);
        email_alani.setBounds(460, 130, 170, 30);

        dogumTarihi_alani.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dogumTarihi_alani.setText("YYYY-AA-GG");
        dogumTarihi_alani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dogumTarihi_alaniMouseClicked(evt);
            }
        });
        dogumTarihi_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogumTarihi_alaniActionPerformed(evt);
            }
        });
        jPanel1.add(dogumTarihi_alani);
        dogumTarihi_alani.setBounds(460, 210, 170, 30);

        sifre_alani.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(sifre_alani);
        sifre_alani.setBounds(460, 170, 170, 30);

        tur1_alani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tur1_alaniMouseClicked(evt);
            }
        });
        jPanel1.add(tur1_alani);
        tur1_alani.setBounds(460, 250, 170, 30);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField5.setText("Tur 1 :");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(320, 250, 130, 30);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField7.setText("Tur 3 :");
        jPanel1.add(jTextField7);
        jTextField7.setBounds(320, 330, 130, 30);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField6.setText("Tur 2 :");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(320, 290, 130, 30);

        jPanel1.add(tur2_alani);
        tur2_alani.setBounds(460, 290, 170, 30);

        jPanel1.add(tur3_alani);
        tur3_alani.setBounds(460, 330, 170, 30);

        kayitOl_alani.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kayitOl_alani.setText("Kayit Ol");
        kayitOl_alani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayitOl_alaniMouseClicked(evt);
            }
        });
        kayitOl_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitOl_alaniActionPerformed(evt);
            }
        });
        jPanel1.add(kayitOl_alani);
        kayitOl_alani.setBounds(340, 400, 120, 30);

        girisyap_alani.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        girisyap_alani.setText("Giris Yap");
        girisyap_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisyap_alaniActionPerformed(evt);
            }
        });
        jPanel1.add(girisyap_alani);
        girisyap_alani.setBounds(480, 400, 110, 30);

        eniyiler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ad", "Tip", "Tur", "Puan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(eniyiler);
        if (eniyiler.getColumnModel().getColumnCount() > 0) {
            eniyiler.getColumnModel().getColumn(0).setResizable(false);
            eniyiler.getColumnModel().getColumn(1).setResizable(false);
            eniyiler.getColumnModel().getColumn(2).setResizable(false);
            eniyiler.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(270, 440, 400, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kayitEkrani.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1030, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dogumTarihi_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogumTarihi_alaniActionPerformed

    }//GEN-LAST:event_dogumTarihi_alaniActionPerformed

    private void dogumTarihi_alaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dogumTarihi_alaniMouseClicked
        dogumTarihi_alani.setText("");
    }//GEN-LAST:event_dogumTarihi_alaniMouseClicked

    private void tur1_alaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tur1_alaniMouseClicked


    }//GEN-LAST:event_tur1_alaniMouseClicked
    public ArrayList<Program> turenyuksek(String tur) {
        ArrayList<Program> program = new ArrayList<Program>();
        for (Program p : islemler.programlar) {

            for (int i = 0; i < p.getTur().size(); i++) {
                if (p.getTur().get(i).equals(tur)) {
                    program.add(p);
                }
            }
        }
        Collections.sort(program);
        ArrayList<Program> dondur = new ArrayList<Program>();
        dondur.add(program.get(0));
        dondur.add(program.get(1));
        return dondur;
    }

    public boolean dogumtarihiKontrol() {
        if (dogumTarihi_alani.getText().length() != 10) {
            System.out.println("burada2");
            return false;
        }
        String yyyy = dogumTarihi_alani.getText().substring(0, 4);
        String aa = dogumTarihi_alani.getText().substring(5, 7);
        String gg = dogumTarihi_alani.getText().substring(8);
        String t1 = dogumTarihi_alani.getText().substring(4, 5);
        String t2 = dogumTarihi_alani.getText().substring(7, 8);
        if (t1.equals("-") && t2.equals("-")) {
            try {
                Integer.parseInt(yyyy);
                int ay = Integer.parseInt(aa);
                int gun = Integer.parseInt(gg);
                if(ay <= 12 && gun <= 31)  {
                    return true;
                }
            } catch (NumberFormatException ex) {
                System.out.println("burada");
                return false;
            }
        } else {
            System.out.println("burada1");
            return false;
        }
        return false;
    }
    private void kayitOl_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitOl_alaniActionPerformed

        boolean tarihUygunMu = dogumtarihiKontrol();
        if (ad_alani.getText().equals("") || email_alani.getText().equals("") || new String(sifre_alani.getPassword()).equals("") || dogumTarihi_alani.getText().equals("")) {
             JOptionPane.showMessageDialog(this, "Kayit Islemi basarisiz...Lutfen tum alanlari tam doldurunuz.");
             return;
        }
        if(!tarihUygunMu) {
            JOptionPane.showMessageDialog(this, "Kayit Islemi basarisiz...Lutfen dogum tarihini yyyy-gg-aa seklinde giriniz!");
             return;
        }
        if(islemler.girisyap(email_alani.getText(), "123")!=0) {
            JOptionPane.showMessageDialog(this, "Bu email zaten mevcut");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) eniyiler.getModel();
        model.setRowCount(0);
        String[] tur = new String[3];
        tur[0] = (String) tur1_alani.getSelectedItem();
        tur[1] = (String) tur2_alani.getSelectedItem();
        tur[2] = (String) tur3_alani.getSelectedItem();
        if (tur[0].equals(tur[1]) || tur[1].equals(tur[2]) || tur[1].equals(tur[2])) {
            JOptionPane.showMessageDialog(this, "Kayit Islemi basarisiz...Lutfen ayni turu birden fazla secmeyiniz.");
            return;
        }
        ArrayList<Program> enyuksekprogram = new ArrayList<Program>();
        enyuksekprogram.addAll(turenyuksek(tur[0]));
        enyuksekprogram.addAll(turenyuksek(tur[1]));
        enyuksekprogram.addAll(turenyuksek(tur[2]));
        int i = 0;
        for (Program p : enyuksekprogram) {
            Object[] eklenecek = {p.getAd(), p.getTip(), tur[i / 2], p.getPuan()};
            model.addRow(eklenecek);
            i++;
        }
        if(islemler.kullaniciEkle(ad_alani.getText(), email_alani.getText(), new String(sifre_alani.getPassword()), dogumTarihi_alani.getText())) {
            JOptionPane.showMessageDialog(this, email_alani.getText() + " Emailine sahip kullanici basariyla kayit edildi.");
            ad_alani.setText("");
            email_alani.setText("");
            sifre_alani.setText("");
            dogumTarihi_alani.setText(dogumtarihi);
        }
    }//GEN-LAST:event_kayitOl_alaniActionPerformed

    private void kayitOl_alaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayitOl_alaniMouseClicked

    }//GEN-LAST:event_kayitOl_alaniMouseClicked

    private void girisyap_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisyap_alaniActionPerformed
        setVisible(false);
        GrisEkrani girisEkrani = new GrisEkrani();
        girisEkrani.setVisible(true);
    }//GEN-LAST:event_girisyap_alaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alani;
    private javax.swing.JTextField dogumTarihi_alani;
    private javax.swing.JTextField email_alani;
    private javax.swing.JTable eniyiler;
    private javax.swing.JButton girisyap_alani;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton kayitOl_alani;
    private javax.swing.JPasswordField sifre_alani;
    private javax.swing.JComboBox<String> tur1_alani;
    private javax.swing.JComboBox<String> tur2_alani;
    private javax.swing.JComboBox<String> tur3_alani;
    // End of variables declaration//GEN-END:variables
}
