/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yeni;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Furkan Turkmen
 */
public class NetflixEkrani extends javax.swing.JFrame {

    Islemler islemler = new Islemler();
    DefaultTableModel model = null;

    /**
     * Creates new form NetflixEkrani
     */
    public NetflixEkrani() {
        initComponents();
        model = (DefaultTableModel) program_tablosu.getModel();
        tumunuEkle();

    }
    public void tumunuEkle() {
         ArrayList<Program> izlenenprogramlar = islemler.kullaniciProgramAtamasi();
        for (Program p : izlenenprogramlar) {
            String durum = "";
            if (p.isIzlenmeDurumu()) {
                durum = "izlendi";
            } else {
                durum = "izlenmedi";
            }
            Object[] eklenecek = {p.getAd(), p.getTip(), p.getBolumsayisi(), p.getUzunluk(), durum, p.getIzlenmeSuresi()};
            model.addRow(eklenecek);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        programArama_alani = new javax.swing.JTextField();
        programagore_ara = new javax.swing.JButton();
        izle_buttonu = new javax.swing.JButton();
        turegore_ara = new javax.swing.JButton();
        tur_text = new javax.swing.JTextField();
        program_text = new javax.swing.JTextField();
        turler = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        program_tablosu = new javax.swing.JTable();
        anapanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setLayout(null);
        jPanel1.add(programArama_alani);
        programArama_alani.setBounds(330, 60, 480, 40);

        programagore_ara.setText("Ara");
        programagore_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programagore_araActionPerformed(evt);
            }
        });
        jPanel1.add(programagore_ara);
        programagore_ara.setBounds(960, 60, 100, 40);

        izle_buttonu.setText("Izle");
        izle_buttonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izle_buttonuActionPerformed(evt);
            }
        });
        jPanel1.add(izle_buttonu);
        izle_buttonu.setBounds(960, 180, 100, 50);

        turegore_ara.setText("Ara");
        turegore_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turegore_araActionPerformed(evt);
            }
        });
        jPanel1.add(turegore_ara);
        turegore_ara.setBounds(960, 120, 100, 40);

        tur_text.setEditable(false);
        tur_text.setText("Tur");
        jPanel1.add(tur_text);
        tur_text.setBounds(830, 120, 110, 40);

        program_text.setEditable(false);
        program_text.setText("Program");
        jPanel1.add(program_text);
        program_text.setBounds(830, 60, 110, 40);

        turler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tumu", "Aksiyon ve Macera", "Anime", "Belgesel", "Bilim Kurgu ve Fantastik Yapimlar", "Bilim ve Doga", "Cocuk ve Aile", "Drama", "Gerilim", "Komedi", "Korku", "Romantik", "Reality Program" }));
        jPanel1.add(turler);
        turler.setBounds(330, 120, 480, 40);

        program_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adi ", "Tip", "Bolum sayisi", "Uzunluk", "Izlenme Durumu", "Izlenme Suresi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(program_tablosu);
        if (program_tablosu.getColumnModel().getColumnCount() > 0) {
            program_tablosu.getColumnModel().getColumn(0).setResizable(false);
            program_tablosu.getColumnModel().getColumn(1).setResizable(false);
            program_tablosu.getColumnModel().getColumn(2).setResizable(false);
            program_tablosu.getColumnModel().getColumn(3).setResizable(false);
            program_tablosu.getColumnModel().getColumn(4).setResizable(false);
            program_tablosu.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 180, 610, 510);

        anapanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mavi.jpg"))); // NOI18N
        jPanel1.add(anapanel);
        anapanel.setBounds(0, -30, 1280, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izle_buttonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izle_buttonuActionPerformed
        int id = program_tablosu.getSelectedRow();

        Object ekle = model.getValueAt(id, 0);
        String izlenmeSuresi = JOptionPane.showInputDialog(this, "Lutfen kac dakika izleyeceginizi giriniz :");
        Object ekle2 = model.getValueAt(id, 5);
        int sure = (int) ekle2;
        try {
            model.setValueAt((Object) (sure + Integer.parseInt(izlenmeSuresi)), id, 5);
            String puanver = JOptionPane.showInputDialog(this, "Lutfen bu programa puan veriniz :");
            int kontrol = islemler.kullaniciProgramUzerineYazma((String) ekle, Integer.parseInt(izlenmeSuresi), Integer.parseInt(puanver));
            if (kontrol == 0) {
                JOptionPane.showMessageDialog(this, "Program izlenemedi.Lutfen herseyi dogru girdinginizden emin olunuz.");
            } else if (kontrol == 1) {
                model.setValueAt((Object) (sure + Integer.parseInt(izlenmeSuresi)), id, 5);
            } else if (kontrol == 2) {
                model.setValueAt((Object) (sure + Integer.parseInt(izlenmeSuresi)), id, 5);
                model.setValueAt((Object) "izlendi", id, 4);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lutfen yanizca sayi giriniz");
        }

    }//GEN-LAST:event_izle_buttonuActionPerformed

    private void turegore_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turegore_araActionPerformed
        model.setRowCount(0);
        ArrayList<Program> izlenenprogramlar = islemler.kullaniciProgramAtamasi();
        String secili_tur = (String) turler.getSelectedItem();
        for (Program p : izlenenprogramlar) {
            if(secili_tur.equals("Tumu")) {
                tumunuEkle();
            }
            else {
                 for (String s : p.getTur()) {
                if (secili_tur.equals(s)) {
                    String durum = "";
                    if (p.isIzlenmeDurumu()) {
                        durum = "izlendi";
                    } else {
                        durum = "izlenmedi";
                    }
                    Object[] eklenecek = {p.getAd(), p.getTip(), p.getBolumsayisi(), p.getUzunluk(), durum, p.getIzlenmeSuresi()};
                    model.addRow(eklenecek);
                }
            }
            }
           

        }
    }//GEN-LAST:event_turegore_araActionPerformed

    private void programagore_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programagore_araActionPerformed
        model.setRowCount(0);
        ArrayList<Program> izlenenprogramlar = islemler.kullaniciProgramAtamasi();
         String aranan_program = (String) programArama_alani.getText();
         for(Program p : izlenenprogramlar) {
             String harfleri_kucult1 = p.getAd().toLowerCase();
             aranan_program = aranan_program.toLowerCase();
             if(harfleri_kucult1.indexOf(aranan_program)!=-1) {
                    String durum = "";
                    if (p.isIzlenmeDurumu()) {
                        durum = "izlendi";
                    } else {
                        durum = "izlenmedi";
                    }
                    Object[] eklenecek = {p.getAd(), p.getTip(), p.getBolumsayisi(), p.getUzunluk(), durum, p.getIzlenmeSuresi()};
                    model.addRow(eklenecek);
             }
         }
    }//GEN-LAST:event_programagore_araActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NetflixEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NetflixEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NetflixEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NetflixEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NetflixEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anapanel;
    private javax.swing.JButton izle_buttonu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField programArama_alani;
    private javax.swing.JTable program_tablosu;
    private javax.swing.JTextField program_text;
    private javax.swing.JButton programagore_ara;
    private javax.swing.JTextField tur_text;
    private javax.swing.JButton turegore_ara;
    private javax.swing.JComboBox<String> turler;
    // End of variables declaration//GEN-END:variables
}
